import Image from "next/image";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';

interface PortfolioCardProps {
  contentType: string;
  keywords: string;
  imagePath: string;
  imageHint: string;
}

const portfolioContent: { [key: string]: { title: string; description: string } } = {
  'fashion, editorial, futuristic': {
    title: 'Futuristic Fashion Shoot',
    description: 'An AI-generated editorial image blending high fashion with sci-fi aesthetics.',
  },
  'corporate, strategy, success': {
    title: 'The New Corporate Playbook',
    description: 'A blog post detailing AI-driven strategies for market success in the next quarter.',
  },
  'travel, adventure, mountains': {
    title: 'Alpine Adventure Awaits',
    description: 'Engaging social media content designed to inspire travel to mountain destinations.',
  },
  'technology, abstract, data visualization': {
    title: 'Data in Motion',
    description: 'An abstract visualization of complex data streams, generated by AI.',
  },
  'cybersecurity, future, network': {
    title: 'Securing Tomorrow\'s Networks',
    description: 'In-depth blog post on the future of AI in cybersecurity.',
  },
  'fashion, luxury, lifestyle': {
    title: 'Luxury Lifestyle Ad',
    description: 'A sophisticated social media ad targeting a high-end fashion audience.',
  },
  'cosmetics, branding, clean': {
    title: 'Clean Beauty Mockup',
    description: 'AI-generated product mockup for a new line of clean cosmetics.',
  },
  'adventure, travel, drone shot': {
    title: 'Drone\'s Eye View',
    description: 'A concept for a travel video featuring breathtaking drone cinematography.',
  },
  'finance, investment, growth': {
    title: 'Mapping Financial Growth',
    description: 'A blog post on leveraging AI for smarter investment strategies.',
  },
  'modern, sustainable, architecture': {
    title: 'Sustainable Urban Living',
    description: 'An architectural render of a modern, eco-friendly building.',
  },
  'food, recipe, delicious': {
    title: 'Gourmet at Home',
    description: 'A social media post showcasing a delicious, easy-to-follow recipe.',
  },
  'startup, technology, simple': {
    title: 'Simple Tech Explainer',
    description: 'Concept for an animated video explaining a complex technology simply.',
  },
};


export function PortfolioCard({ contentType, keywords, imagePath, imageHint }: PortfolioCardProps) {
  const content = portfolioContent[keywords] || { title: 'AI-Generated Content', description: 'A piece of content generated by our advanced AI prompts.' };
  
  return (
    <Card className="group flex flex-col h-full overflow-hidden transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-2xl hover:shadow-primary/20 bg-background/50 backdrop-blur-sm border-border/20 rounded-2xl">
      <div className="aspect-video relative overflow-hidden">
        <Image
          src={imagePath}
          alt={content.title}
          width={600}
          height={400}
          className="object-cover transition-transform duration-500 ease-in-out group-hover:scale-105 w-full h-auto"
          data-ai-hint={imageHint}
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/30 to-transparent" />
      </div>
      <CardHeader className="flex-grow">
        <CardTitle>{content.title}</CardTitle>
      </CardHeader>
      <CardContent>
        <CardDescription>{content.description}</CardDescription>
      </CardContent>
    </Card>
  );
}
