import HeaderSection from '@/components/header-section';
import { Separator } from '@/components/ui/separator';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import Link from 'next/link';

export default function TermsOfUse() {
  return (
    <div className="flex flex-col min-h-screen bg-background text-foreground isolate">
      <div className="fixed inset-0 h-full w-full bg-background bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px] -z-10"></div>
      <div className="fixed inset-0 -z-9 pointer-events-none bg-[radial-gradient(circle_at_50%_200px,#E6E6FA66,transparent)] dark:bg-[radial-gradient(circle_at_50%_200px,#B0E2FF33,transparent)]"></div>
      
      <HeaderSection />

      <main className="flex-1 w-full max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="pt-24 pb-16">
            <Card className="bg-card/60 backdrop-blur-lg border-border/20 shadow-lg">
                <CardHeader>
                    <CardTitle className="text-3xl font-bold font-headline tracking-tight">Terms of Use</CardTitle>
                    <p className="text-sm text-muted-foreground pt-1">Last Updated: August 5, 2025</p>
                </CardHeader>
                <CardContent className="space-y-4 text-foreground/80">
                    <p>Welcome to IncDrops! These Terms of Use govern your access to and use of the IncDrops website and our AI-powered trend report services. By accessing or using our services, you agree to be bound by these Terms. If you do not agree, you are not authorized to use IncDrops.</p>

                    <h3 className="font-bold text-xl pt-4 font-headline text-primary-foreground">1. The IncDrops Service</h3>
                    <p>IncDrops provides curated trend reports generated by a proprietary AI. These reports are for informational and inspirational purposes only. While our AI uses real-time data to forecast trends, the reports are not a guarantee of future outcomes, and IncDrops is not responsible for any actions you take based on the information provided.</p>
                    
                    <h3 className="font-bold text-xl pt-4 font-headline text-primary-foreground">2. Payment and Refunds</h3>
                    <p><strong>Pricing:</strong> Each trend report is available for a one-time fee of $5.</p>
                    <p><strong>Payment:</strong> All payments are processed securely through a third-party payment provider. IncDrops does not store your credit card information.</p>
                    <p><strong>Refunds:</strong> Due to the nature of our digital product, all sales are final, and we do not offer refunds once a report has been generated and delivered.</p>

                    <h3 className="font-bold text-xl pt-4 font-headline text-primary-foreground">3. Intellectual Property and Content Use</h3>
                    <p><strong>Your Query:</strong> When you submit an idea, hashtag, or product query to generate a report, you grant IncDrops a license to use that query for the purpose of generating your report and improving our services.</p>
                    <p><strong>The Trend Report:</strong> Once you purchase a report, you are granted a non-exclusive, non-transferable license to use the report for your personal or internal business purposes.</p>
                    <p><strong>Restrictions:</strong> You may not republish, sell, rent, or redistribute the IncDrops trend reports or any of our site's content to third parties. You may, however, use the insights from the report to inspire and inform your own projects.</p>
                    <p><strong>IncDrops's IP:</strong> All content, design, and technology on the IncDrops website, including the AI, is the exclusive property of IncDrops and protected by intellectual property laws.</p>
                    
                    <h3 className="font-bold text-xl pt-4 font-headline text-primary-foreground">4. Disclaimer of Warranties</h3>
                    <p>Our service and all reports are provided on an "as is" and "as available" basis. IncDrops makes no warranties, express or implied, regarding the accuracy, completeness, or reliability of the reports or the service itself. We disclaim all warranties, including but not limited to, implied warranties of merchantability, fitness for a particular purpose, and non-infringement.</p>

                    <h3 className="font-bold text-xl pt-4 font-headline text-primary-foreground">5. Limitation of Liability</h3>
                    <p>To the maximum extent permitted by law, IncDrops shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising from your use of or inability to use our services or reports.</p>
                </CardContent>
            </Card>
        </div>
      </main>

      <footer className="w-full mt-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <Separator />
          <div className="flex flex-col sm:flex-row justify-between items-center py-8 text-muted-foreground text-sm">
            <span>© {new Date().getFullYear()} IncDrops.com. All rights reserved.</span>
            <div className="flex gap-4 mt-4 sm:mt-0">
                <Link href="/terms" className="hover:text-accent transition-colors">Terms of Use</Link>
                <Link href="/privacy" className="hover:text-accent transition-colors">Privacy Policy</Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
